---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: debian-8.2
    run_list:
      - recipe[apt::default]
  - name: debian-7.9
    run_list:
      - recipe[apt::default]
  - name: centos-7.2
    run_list:
      - recipe[yum::default]
  - name: centos-6.7
    run_list:
      - recipe[yum::default]
  - name: centos-5.11
    run_list:
      - recipe[yum::default]
  - name: freebsd-10.2
    run_list:
      - recipe[freebsd::default]
  - name: windows-2012r2
    run_list:
      - recipe[windows::default]

suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        config: &default-config
          bootstrap: true
          server: true
          datacenter: FortMeade
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
  - name: git
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        config: *default-config
        installation:
          provider: git
    excludes:
      - windows-2012r2
  - name: webui
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        config:
          bootstrap: true
          server: true
          ui: true
          datacenter: FortMeade
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
  - name: acl
    run_list:
      - recipe[consul::default]
      - recipe[consul::client_gem]
      - recipe[consul_spec::acl]
    attributes:
      consul:
        config:
          bootstrap: true
          server: true
          datacenter: fortmeade
          acl_master_token: doublesecret
          acl_datacenter: fortmeade
          acl_default_policy: deny
    excludes:
      - windows-2012r2
      - centos-7.2
      - centos-6.7
      - centos-5.11
